apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: nginx
spec:
  lookupPolicy:
    local: true
  tags:
  - from: 
      kind: DockerImage
      name: registry.access.redhat.com/ubi9/nginx-120:latest
    name: latest
    referencePolicy:
      type: Local
