apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backend
  namespace: client-certificate-auth
spec:
  secretName: backend-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: auth.client-certificate-auth.svc
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  # dnsNames:
  #   - auth.client-certificate-auth.svc
  issuerRef:
    name: ca
    kind: Issuer
